/* How ASV works, in plain terms for staff and project stakeholders. */
Shell.init({ page: "guide.html" }, function (user, view) {
  const P = (t, b) => '<section class="panel"><header>' + t + '</header><div class="body">' + b + "</div></section>";
  view.innerHTML = '<div class="pagehead"><div><div class="crumb">Reference</div><h1>How signature verification works</h1></div></div><div class="cols even"><div>' +
    P("What the system does", '<ol style="margin:0;padding-left:20px"><li><b>Receive.</b> The branch scans the signed instruction and an Operations Officer registers the case.</li><li><b>Extract.</b> The system finds the handwriting on the scan and crops each signature. The officer can untick a handwritten date or merge a split signature.</li><li><b>Look up.</b> The specimen of each authorised signatory comes from the specimen register, using the account\'s signing mandate.</li><li><b>Compare.</b> Each signature gets a score from 0 to 100 against the specimen. 70 and above passes.</li><li><b>Route.</b> A match goes to the approver for the amount. Anything else goes to fraud review or back to the customer.</li></ol>') +
    P("Three outcomes", '<table class="grid"><tbody><tr><td><span class="st pass">Likely match</span></td><td>Every signature matches an authorised signatory and the mandate is met. The case can be submitted for approval.</td></tr><tr><td><span class="st flag">Flagged</span></td><td>A signature scored below the pass score or could not be compared reliably. A fraud analyst reviews it and may clear it after a callback.</td></tr><tr><td><span class="st fail">Mandate not met</span></td><td>The signatures are genuine but too few, or one person signed twice. The case returns to the customer.</td></tr></tbody></table>') +
    "</div><div>" +
    P("Who does what", '<table class="grid"><tbody><tr><td><b>Operations Officer</b></td><td>Registers, verifies and submits.</td></tr><tr><td><b>Fraud Review Analyst</b></td><td>Reviews flagged cases and confirms or clears with a callback.</td></tr><tr><td><b>Senior Operations Officer</b></td><td>Approves up to Level 1.</td></tr><tr><td><b>Branch Manager</b></td><td>Approves up to Level 2 and all fraud-cleared cases.</td></tr><tr><td><b>Head of Operations</b></td><td>Approves any amount.</td></tr><tr><td><b>Internal Auditor</b></td><td>Reads cases and the audit trail.</td></tr></tbody></table>') +
    P("Limits to keep in mind", '<ul style="margin:0;padding-left:18px"><li>The system is only as good as the specimen on file. Compare each signature with the signatory the mandate requires.</li><li>Genuine signatures vary with writing conditions, age and scan quality. A low score is a reason to look closer, not proof of forgery.</li><li>Scans carry no pen pressure, speed or stroke order.</li><li>A score never authorises a high-value instruction. A second person always approves.</li></ul>') +
    "</div></div>";
});
