/* Policy and limits: the rules the system enforces, written so a reviewer can check them. */
Shell.init({ page: "policy.html" }, function (user, view) {
  const A = APP, esc = UI.esc, P = A.POLICY;
  const yes = '<span class="st pass">Yes</span>', no = '<span class="faint">No</span>';
  const caps = [[A.BRAND.register, ["maker"]], ["Run signature verification", ["maker"]], ["Refer or return to customer", ["maker"]], ["Clear or confirm a flagged signature", ["fraud"]], ["Approve, reject or return", ["checker", "manager", "head"]], ["View audit trail", ["auditor", "manager", "head"]]];
  const panel = (t, b, flush) => '<section class="panel"><header>' + t + '</header><div class="body' + (flush ? " flush" : "") + '">' + b + "</div></section>";
  view.innerHTML = '<div class="pagehead"><div><div class="crumb">Reference</div><h1>Policy and limits</h1></div></div><div class="cols even"><div>' +
    panel("Signature verification", '<div class="kv" style="grid-template-columns:1fr 1fr"><div><span>Pass score</span><b>' + P.passScore + ' and above</b></div><div><span>Below pass score</span><b>Flag for fraud review</b></div></div><p class="small muted" style="margin:10px 0 0">The score is a similarity measure from 0 to 100. A score never authorises a payment. Overlapping, cut-off or faint signatures are flagged as not reliably comparable. In this demonstration the score comes from a demonstration engine, not a validated bank model.</p>') +
    panel("Approval authority", '<table class="grid"><thead><tr><th>Level</th><th>Amount in MYR equivalent</th><th>Approver</th></tr></thead><tbody>' + P.levels.map((l, i) => "<tr><td><b>" + l.n + "</b></td><td>" + (i ? "Above " + P.levels[i - 1].upTo.toLocaleString("en-US") + (l.upTo === Infinity ? "" : " to " + l.upTo.toLocaleString("en-US")) : "Up to " + l.upTo.toLocaleString("en-US")) + "</td><td>" + esc(l.who) + "</td></tr>").join("") + '</tbody></table><p class="small muted" style="margin:10px 12px">A currency with no exchange rate on file goes to Level " + P.levels.length + ". A case cleared in review after a flag needs at least Level 2.</p>', true) +
    panel("Four-eyes rules", '<ul style="margin:0;padding-left:18px"><li>The officer who registers a case cannot approve it.</li><li>The analyst who clears a flagged signature cannot approve the case.</li><li>An approver cannot approve above their authority level.</li><li>Rejections, returns and fraud decisions need a written note.</li><li>Clearing a flag needs a callback reference.</li><li>Every action is written to the audit trail with user, role and time.</li></ul>') +
    "</div><div>" +
    panel("Who can do what", '<table class="grid"><thead><tr><th>Action</th>' + Object.keys(A.ROLES).map((r) => "<th>" + esc(A.ROLES[r].short === "Approver" ? A.ROLES[r].title.split(" ")[0] + " " + A.ROLES[r].title.split(" ").slice(-1)[0] : A.ROLES[r].title) + "</th>").join("") + "</tr></thead><tbody>" + caps.map((c) => '<tr><td style="min-width:200px">' + c[0] + "</td>" + Object.keys(A.ROLES).map((r) => '<td class="r">' + (c[1].includes(r) ? yes : no) + "</td>").join("") + "</tr>").join("") + "</tbody></table>", true) +
        panel("Service targets and session", '<div class="kv" style="grid-template-columns:1fr 1fr">' + Object.keys(A.TYPES).map((k) => "<div><span>" + esc(A.TYPES[k].label) + "</span><b>" + (A.TYPES[k].slaHours >= 24 ? A.TYPES[k].slaHours / 24 + " day" : A.TYPES[k].slaHours + " hours") + "</b></div>").join("") + '<div><span>Idle sign-out</span><b>' + P.sessionMinutes + ' minutes</b></div></div><p class="small muted" style="margin:10px 0 0">Three failed sign-in attempts lock a staff ID for 2 minutes.</p>') +
    panel("Indicative exchange rates to MYR", '<div class="small" style="columns:3">' + Object.keys(A.FX).map((k) => k + " " + A.FX[k]).join("<br>") + "</div>") +
    panel("Demonstration data", '<p class="small muted" style="margin:0 0 8px">Cases and the audit trail are stored in this browser only. Resetting restores the starting data and removes cases you created.</p><button class="btn danger" id="reset">Reset demonstration data</button>') + "</div></div>";
  view.querySelector("#reset").onclick = async () => {
    if (!(await UI.confirm("Reset demonstration data", "<p style=\"margin:0\">This removes every case and audit event you created and restores the starting data. You will stay signed in.</p>", "Reset", true))) return;
    DB.reset(); DB.log(user, "auth", "Demo data reset", "", ""); UI.toast("Demonstration data restored.", "ok");
  };
});
